"""Stage: battery-report. Renders analysis.md for a multi-arm battery.

Generated, not written by hand, so the prose cannot drift from the numbers. It keeps apart
the four things `ltlp/report.py` keeps apart for a single experiment — observed behavioural
change, measured performance change, statistical uncertainty, confounds — and adds the three
a battery has to separate as well: what one phrase did, what a family of phrases did, and
what survives having screened many phrases at once.

No sentence generated here asserts that a model is motivated, wants anything, or tries
harder. See METHODOLOGY.md, "Interpretation rule".
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from . import battery, indicators, judge, runner, util

PRIMARY = battery.PRIMARY
CONFIRMATORY = battery.CONFIRMATORY
REFS = battery.CORE_REFERENCES


def _f(x: Optional[float], nd: int = 3) -> str:
    return "n/a" if x is None else ("%.*f" % (nd, x))


def _ci(ci, nd: int = 3) -> str:
    return "n/a" if not ci else "[%.*f, %.*f]" % (nd, ci[0], nd, ci[1])


def _pct(x: Optional[float]) -> str:
    return "n/a" if x is None else "%.0f%%" % (100 * x)


def _verdict_word(v: str) -> str:
    return {"treatment": "**yes**", "reference": "**worse**",
            "not_demonstrated": "no"}.get(v, "no")


def render(cfg, doc: Dict[str, Any]) -> str:
    counts = doc["counts"]
    meta = doc["run_meta"]
    is_pilot = doc["mode"] == "pilot"
    arms = {c["id"]: c for c in cfg.conditions}
    L: List[str] = []
    A = L.append

    A("# Analysis: Experiment %s - Phrase Battery" % doc["experiment_id"])
    A("")
    A("*Generated by `scripts/experiment.py battery-report` from "
      "`analysis/battery_summary.json`. Do not edit by hand: re-run the stage instead.*")
    A("")
    if is_pilot:
        A("> **This is a PILOT run.** Its purpose is to prove the workflow end to end, not "
          "to answer the research question. With %d tasks it is not powered for inference, "
          "no conclusion below is evidence about any phrase, and no arm's confidence stage "
          "moves." % counts["tasks"])
        A("")
    if (meta.get("generation") or {}).get("backend") == "mock":
        A("> **MOCK RUN. Synthetic output, never a scientific result.** Every generation "
          "here came from the offline deterministic stand-in backend. The numbers below "
          "exercise the analysis code and mean nothing about any phrase.")
        A("")

    # ------------------------------------------------------------------ 1
    A("## 1. What was run")
    A("")
    A("| Field | Value |")
    A("|---|---|")
    A("| Run ID | `%s` |" % doc["run_id"])
    A("| Mode | %s |" % doc["mode"])
    A("| Date | %s |" % meta.get("prepared_at"))
    A("| Generation model | `%s` |" % (meta.get("generation", {}) or {}).get("model"))
    A("| Generation backend | `%s` |" % (meta.get("generation", {}) or {}).get("backend"))
    A("| Judge model | `%s` |" % (meta.get("judging", {}) or {}).get("model"))
    A("| Sampling settings | %s |" % ((meta.get("generation", {}) or {}).get(
        "temperature") or "not exposed by this backend"))
    A("| Master seed | `%s` |" % doc["seed"])
    A("| Arms | %d (%d treatment, %d combination, 3 shared control) |"
      % (counts["arms"], counts["treatment_arms"], counts["combo_arms"]))
    A("| Behavioural families | %d |" % counts["families"])
    A("| Tasks x arms x repetitions | %d x %d x %d = %d |"
      % (counts["tasks"], counts["arms"], counts["repetitions"],
         counts["tasks"] * counts["arms"] * counts["repetitions"]))
    A("| Generations present | %d |" % counts["generations"])
    A("| Blind judgments | %d |" % counts["blind_judged"])
    A("| Pairwise comparisons | %d |" % counts["pairwise_judged"])
    A("| Core contrasts | %d |" % counts["core_contrasts"])
    A("| Task set version | `%s` |" % doc["spec_lock"]["versions"].get("tasks"))
    A("| Rubric version | `%s` |" % doc["spec_lock"]["versions"].get("rubric"))
    A("| Evaluation version | `%s` |" % doc["spec_lock"]["versions"].get("evaluation_version"))
    A("")
    A("Shared control arms, byte-identical to Experiment 001's conditions A, B and D:")
    A("")
    A("| ID | Role | Appended text |")
    A("|---|---|---|")
    for cid in ("A", "B", "D"):
        c = arms[cid]
        A("| %s | %s | %s |" % (cid, c["name"].replace("_", " "),
                                "*(nothing)*" if not c["suffix"] else "`%s`" % c["suffix"]))
    A("")
    A("Every treatment arm is measured against all three. `vs_A` asks whether the phrase "
      "beats no added text; `vs_B` and `vs_D` are what isolate the phrase from the mere "
      "presence of appended text, and from a plain instruction.")
    A("")

    # ------------------------------------------------------------------ 2
    A("## 2. The arms")
    A("")
    A("| Arm | Family | Role | Chars | Phrase |")
    A("|---|---|---|---:|---|")
    for row in sorted(doc["phrases"].values(), key=lambda r: r["arm_id"]):
        A("| `%s` | %s %s | %s | %d | %s |" % (
            row["arm_id"], row["family"], row["family_name"], row["role"],
            row["suffix_chars"], row["phrase"]))
    A("")
    A("Combination arms append the phrase and then the canonical effort instruction:")
    A("")
    A("| Arm | Built from | Family |")
    A("|---|---|---|")
    for k in sorted(doc["combos"].values(), key=lambda r: r["arm_id"]):
        A("| `%s` | `%s` %s | %s%s |" % (
            k["arm_id"], k["phrase_arm"], k["phrase"], k["family_name"],
            " **(placebo control for the combo comparison)**"
            if k["role"] == "placebo_combo" else ""))
    A("")

    # ------------------------------------------------------------------ 3
    A("## 3. Observed behavioural change")
    A("")
    A("What the responses looked like, pooled by family. These are **surface measurements "
      "of text**, computed by regular expressions over the output. They are heuristic "
      "proxies: a response can check its work without using any of the marker phrases, and "
      "can use the phrases without checking anything. Read them as description, not as "
      "measurement of effort.")
    A("")
    fam_members = {fid: f["members"] for fid, f in doc["families"].items()}
    cols = [("A", "A control"), ("B", "B generic enc."), ("D", "D effort instr.")] + \
           [(fid, "%s %s" % (fid, doc["families"][fid]["name"].split()[0]))
            for fid in sorted(doc["families"])]
    A("| Indicator | " + " | ".join(label for _, label in cols) + " |")
    A("|---" * (len(cols) + 1) + "|")
    for field in indicators.INDICATOR_FIELDS:
        means = doc["indicator_means"].get(field, {})
        cells = []
        for key, _ in cols:
            if key in ("A", "B", "D"):
                v = (means.get(key) or {}).get("mean")
            else:
                vals = [(means.get(a) or {}).get("mean") for a in fam_members.get(key, [])]
                vals = [x for x in vals if x is not None]
                v = sum(vals) / len(vals) if vals else None
            cells.append(_f(v, 1 if field == "response_words" else 3))
        A("| %s | %s |" % (indicators.INDICATOR_LABELS[field], " | ".join(cells)))
    A("")

    # ------------------------------------------------------------------ 4
    A("## 4. Measured task performance, by arm")
    A("")
    A("Two independent measurements: a deterministic objective score from planted issues "
      "and machine-checkable constraints, and a blind judge's **task success** rating, the "
      "pre-registered primary outcome. Arms are ordered by objective score, which is the "
      "measure with headroom on this task set (see section 9).")
    A("")
    prim = doc["arm_means"][PRIMARY]
    obj = doc["arm_means"][CONFIRMATORY]
    order = sorted(arms, key=lambda a: -(obj.get(a, {}).get("mean") or -9e9))
    A("| Arm | Name | n | Objective | 95% CI | Judge task success | 95% CI |")
    A("|---|---|---:|---:|---|---:|---|")
    for a in order:
        o, p = obj.get(a, {}), prim.get(a, {})
        A("| `%s` | %s | %d | %s | %s | %s | %s |" % (
            a, arms[a]["name"].replace("_", " "), o.get("n", 0),
            _f(o.get("mean")), _ci(o.get("ci95")), _f(p.get("mean")), _ci(p.get("ci95"))))
    A("")

    # ------------------------------------------------------------------ 5
    A("## 5. Phrase leaderboard")
    A("")
    A("Task-level mean paired differences against each reference. Ordered by the primary "
      "outcome against the empty control. A positive number favours the phrase.")
    A("")
    A("| # | Arm | Phrase | Family | vs A | vs B | vs D | 95% CI vs A | Holm p | BH q | Win rate | Decision |")
    A("|---:|---|---|---|---:|---:|---:|---|---:|---:|---:|---|")
    for i, r in enumerate(doc["leaderboard"], 1):
        A("| %d | `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            i, r["arm_id"], r["phrase"][:46] + ("..." if len(r["phrase"]) > 46 else ""),
            r["family"], _f(r["primary_vs_A"]), _f(r["primary_vs_B"]), _f(r["primary_vs_D"]),
            _ci(r["primary_ci_vs_A"]), _f(r["holm_p_vs_A"], 4), _f(r["bh_q_vs_A"], 4),
            _pct(r["win_rate_vs_A"]), r["classification"]))
    A("")
    A("The same ordering on the objective score, which no judge touched:")
    A("")
    A("| # | Arm | Family | Objective vs A | vs B | vs D | Best task type | Worst task type |")
    A("|---:|---|---|---:|---:|---:|---|---|")
    for i, r in enumerate(sorted(doc["leaderboard"],
                                 key=lambda x: -(x["objective_vs_A"]
                                                 if x["objective_vs_A"] is not None
                                                 else -9e9)), 1):
        A("| %d | `%s` | %s | %s | %s | %s | %s | %s |" % (
            i, r["arm_id"], r["family"], _f(r["objective_vs_A"]), _f(r["objective_vs_B"]),
            _f(r["objective_vs_D"]), r["best_task_family"] or "n/a",
            r["worst_task_family"] or "n/a"))
    A("")

    # ------------------------------------------------------------------ 6
    A("## 6. The three questions, per phrase")
    A("")
    A("Decision rule, fixed in `PREREGISTRATION.md` before any data existed: a contrast "
      "counts as demonstrated only if the treatment's point estimate is higher, the 95%% "
      "interval excludes zero, and the Holm-adjusted permutation p is below %.2f, on the "
      "primary outcome, with Holm computed across that phrase's own three contrasts. "
      "**Positive** additionally requires an active control and survival of the "
      "battery-wide FDR correction."
      % battery.ALPHA)
    A("")
    A("| Arm | Beats control? | Beats encouragement? | Beats effort instruction? | Decision |")
    A("|---|---|---|---|---|")
    for r in doc["leaderboard"]:
        rec = doc["phrases"][r["arm_id"]]
        cells = [_verdict_word(rec["contrasts"][PRIMARY]["%s_vs_%s" % (r["arm_id"], ref)]
                               ["verdict"]) for ref in REFS]
        A("| `%s` | %s | %s | %s | %s |" % (r["arm_id"], cells[0], cells[1], cells[2],
                                            rec["classification"]))
    A("")
    for r in doc["leaderboard"]:
        rec = doc["phrases"][r["arm_id"]]
        A("**`%s` — %s** (%s%s)  " % (
            rec["arm_id"], rec["phrase"], rec["family_name"],
            ", also %s" % rec["secondary_family_name"] if rec["secondary_family_name"] else ""))
        A("*%s* — %s. %s" % (rec["classification"], rec["classification_reason"],
                             "Registered mechanism: %s" % rec["mechanism"]))
        A("")
        A("| Contrast | Primary diff | 95% CI | dz | Holm p | BH q | Objective diff | Consistency |")
        A("|---|---:|---|---:|---:|---:|---:|---:|")
        for ref in REFS:
            cid = "%s_vs_%s" % (rec["arm_id"], ref)
            c = rec["contrasts"][PRIMARY][cid]
            o = rec["contrasts"][CONFIRMATORY][cid]
            A("| `%s` | %s | %s | %s | %s | %s | %s | %s of %d |" % (
                cid, _f(c.get("task_level_mean_difference")), _ci(c.get("ci95_task_level")),
                _f(c.get("cohens_dz_task_level"), 2), _f(c.get("holm_p_within_phrase"), 4),
                _f(c.get("bh_q_across_battery"), 4),
                _f(o.get("task_level_mean_difference")),
                _pct(c.get("consistency_across_discriminating_tasks")),
                c.get("discriminating_tasks", 0)))
        for cav in rec["caveats"]:
            A("")
            A("> Adverse effect: %s" % cav)
        A("")

    # ------------------------------------------------------------------ 7
    A("## 7. Category level: do behavioural families move the numbers?")
    A("")
    A("Each family pools the task-level differences of its member arms, averaging over arms "
      "**within** each task so the task stays the unit of analysis. Pooling is the whole "
      "reason a battery can say anything about a family rather than about one phrase: a "
      "family contrast carries roughly as many observations as it has members. Shared "
      "control arms are references here, not pooled members. p values are BH-adjusted "
      "across the %d families." % counts["families"])
    A("")
    A("| Family | Members | Objective vs A | 95% CI | BH q | Primary vs A | 95% CI | BH q | vs B | vs D |")
    A("|---|---:|---:|---|---:|---:|---|---:|---:|---:|")
    for r in doc["family_leaderboard"]:
        A("| %s %s | %d | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            r["family_id"], r["name"], r["n_members"],
            _f(r["objective_vs_A"]), _ci(r["objective_ci_vs_A"]), _f(r["objective_bh_q"], 4),
            _f(r["primary_vs_A"]), _ci(r["primary_ci_vs_A"]), _f(r["primary_bh_q"], 4),
            _f(r["primary_vs_B"]), _f(r["primary_vs_D"])))
    A("")
    A("Family F9 is the floor. It contains the two placebo arms, which append irrelevant "
      "text of comparable length. Any family that does not separate from F9 has not shown "
      "an effect of meaning; it has shown an effect of appending text.")
    A("")

    # ------------------------------------------------------------------ 8
    A("## 8. Does emotional framing amplify an explicit instruction?")
    A("")
    A("Each combination arm appends its phrase and then the canonical effort instruction. "
      "`vs D` asks whether the phrase adds anything to the instruction alone; `vs` its own "
      "phrase arm asks whether the instruction adds anything to the phrase alone.")
    A("")
    placebo = doc.get("placebo_combo")
    if placebo:
        A("The last column is the one that settles the question. `%s` is built on a "
          "**placebo** phrase, so it measures what appending *any* sentence plus the "
          "instruction does. A phrase amplifies the instruction only if its lift over the "
          "instruction exceeds the placebo's lift; that difference in differences is "
          "reported with its own interval." % placebo)
        A("")
    A("| Arm | Phrase family | vs D (objective) | vs D (primary) | vs own phrase arm (objective) | Lift over placebo combo (objective) | 95% CI |")
    A("|---|---|---:|---:|---:|---:|---|")
    for k in sorted(doc["combos"].values(), key=lambda r: r["arm_id"]):
        kid = k["arm_id"]
        oD = k["contrasts"][CONFIRMATORY].get("%s_vs_D" % kid, {})
        pD = k["contrasts"][PRIMARY].get("%s_vs_D" % kid, {})
        oP = k["contrasts"][CONFIRMATORY].get("%s_vs_%s" % (kid, k["phrase_arm"]), {})
        did = k["contrasts"][CONFIRMATORY].get(
            "%s_vs_%s_lift_over_placebo" % (kid, placebo), {}) if placebo else {}
        A("| `%s` | %s%s | %s | %s | %s | %s | %s |" % (
            kid, k["family_name"],
            " *(placebo)*" if k["role"] == "placebo_combo" else "",
            _f(oD.get("task_level_mean_difference")),
            _f(pD.get("task_level_mean_difference")),
            _f(oP.get("task_level_mean_difference")),
            _f(did.get("task_level_mean_difference")) if did else "reference",
            _ci(did.get("ci95_task_level")) if did else "-"))
    A("")

    # ------------------------------------------------------------------ 9
    A("## 9. Statistical uncertainty and multiplicity")
    A("")
    A("Pairing is within (task, repetition). Paired differences are averaged to the task "
      "level, and the **task** is the unit for both the permutation test and the bootstrap, "
      "because responses to the same task are not independent. The permutation test flips "
      "the sign of each task-level difference, which is the exchangeability assumption "
      "implied by the null that the appended text does nothing. It is exact at %d tasks."
      % counts["tasks"])
    A("")
    A("Three levels of multiplicity, all fixed before the run:")
    A("")
    A("1. **Per phrase — the decision rule.** %s." % doc["multiplicity"]["level_1_decision_rule"])
    A("2. **Across the battery — the screening claim.** %s, at q = %.2f. A phrase described "
      "as a battery winner must survive this; it is the correction for having looked at %d "
      "phrases." % (doc["multiplicity"]["level_2_screening"], doc["fdr_q"],
                    counts["treatment_arms"]))
    A("3. **Across families.** %s, at q = %.2f."
      % (doc["multiplicity"]["level_3_families"], doc["fdr_q"]))
    A("")
    A("%s." % doc["multiplicity"]["also_reported"].capitalize())
    A("")
    disc = [(r["arm_id"], doc["phrases"][r["arm_id"]]["contrasts"][PRIMARY]
             ["%s_vs_A" % r["arm_id"]].get("discriminating_tasks", 0))
            for r in doc["leaderboard"]]
    if disc:
        vals = [d for _, d in disc]
        A("**Effective n.** On a saturated measure the quantity governing power is not the "
          "task count but the number of tasks whose scores actually differ between arms. "
          "Across the %d treatment arms, the `vs_A` contrast on the primary outcome "
          "discriminated on a median of %d of %d tasks (range %d to %d). A sign-flip test "
          "on k discriminating tasks cannot return a p below 2/2^k, so an arm with few of "
          "them was arithmetically incapable of significance before the data arrived."
          % (len(disc), sorted(vals)[len(vals) // 2], counts["tasks"], min(vals), max(vals)))
        A("")

    # ------------------------------------------------------------------ 10
    A("## 10. Possible confounds")
    A("")
    echo = doc["blinding"]
    A("- **Blinding leakage.** %d of %d responses (%s) repeated their arm's text back in "
      "the output, which a judge could in principle recognise. Outputs were never edited. "
      "Experiment 001 recorded that leakage can *penalise* a treatment rather than flatter "
      "it, and the direction is not predictable in advance."
      % (echo["condition_echo_count"], counts["generations"],
         _f(echo["condition_echo_rate"])))
    leaky = sorted(((a, v["echoes"], v["n"]) for a, v in doc["echo_by_arm"].items()
                    if v["echoes"]), key=lambda x: -x[1])[:6]
    if leaky:
        A("  Arms with the most leakage: %s."
          % ", ".join("`%s` %d/%d" % (a, e, n) for a, e, n in leaky))
    A("- **Prompt length.** Condition A is shorter than every other arm by construction, and "
      "the arms differ from each other. Per-arm suffix length is in section 2 so a length "
      "gradient would be visible; the B, D and placebo arms are what separate meaning from "
      "length.")
    A("- **Shared control arms.** A, B and D were generated once and serve as the reference "
      "for every treatment arm. Execution order was shuffled globally from the master seed, "
      "so no arm sits in its own time window. The cost is that contrasts sharing a reference "
      "are correlated with one another, which affects the leaderboard's joint reading rather "
      "than any single paired test, and is why the FDR level exists.")
    A("- **Judge model.** The judge is `%s` and the generator is `%s`.%s" % (
        (meta.get("judging", {}) or {}).get("model"),
        (meta.get("generation", {}) or {}).get("model"),
        " These are the same model, so a preference for its own output style cannot be "
        "ruled out." if (meta.get("judging", {}) or {}).get("model")
        == (meta.get("generation", {}) or {}).get("model") else ""))
    A("- **Length bias in judging.** Judges commonly prefer longer answers. Section 3 "
      "reports mean response length; the objective score is immune to it and is the check.")
    A("- **Harness context.** Generations ran through the `claude` CLI, which supplies its "
      "own system preamble. It is identical across arms, so internal validity holds, but "
      "these results describe behaviour in that harness rather than of a bare API call.")
    A("- **Sampling settings.** Not exposed by this backend, so run-to-run variation cannot "
      "be attributed to a known temperature.")
    A("- **Single model, single phrase position.** Every phrase was appended at the end of "
      "the prompt, to one model. Role-priming arms are the most affected: a role is "
      "conventionally set in a system prompt, and testing one as a trailing sentence tests "
      "that phrase in that position, not role priming in general.")
    A("- **Heuristic indicators.** Everything in section 3 is regular-expression counting "
      "over text. It measures phrasing, not cognition.")
    A("- **Ceiling.** The primary outcome is partly saturated on this task set; this was "
      "measured in Experiment 001 and declared in section 4.1 of the preregistration before "
      "this battery ran. It is why the objective score is co-reported rather than relegated.")
    A("")

    # ------------------------------------------------------------------ 11
    A("## 11. Interpretation rule")
    A("")
    A("This experiment measures text. It does not measure motivation.")
    A("")
    A("Where this repository uses the words *motivation*, *effort* or *seriousness*, they "
      "name hypotheses about observable output behaviour: more complete reasoning, more "
      "checking, better constraint following, fewer errors, higher task success. They are "
      "not claims that a model wants anything, tries harder, or experiences encouragement. "
      "A difference between arms here would show that a string of text changed a "
      "distribution over outputs. That is a fact about prompting, not about inner life.")
    A("")
    A("## 12. Confidence stage")
    A("")
    if is_pilot:
        A("All arms remain at **Observed**. A pilot validates the workflow and cannot move "
          "any arm along the ladder.")
    else:
        A("Promotion off **Observed** is a judgement to record by hand in the experiment "
          "README after reading the results above, not something this script asserts. "
          "`T01` is the exception worth noting explicitly: it re-runs Experiment 001's "
          "phrase, so its agreement or disagreement with that experiment is a check on this "
          "battery's instruments rather than a new finding about the phrase.")
    A("")
    A("## Raw data")
    A("")
    for f, d in (("raw/", "every generation, write once, with `INDEX.jsonl` as a sha256 ledger"),
                 ("analysis/samples.csv", "one row per generation"),
                 ("analysis/results.csv", "aggregate metrics and contrasts"),
                 ("analysis/phrase_results.csv", "one row per phrase arm"),
                 ("analysis/family_results.csv", "one row per behavioural family"),
                 ("analysis/summary.json", "the machine-readable contrast set"),
                 ("analysis/battery_summary.json", "the machine-readable result this report renders"),
                 ("manifest.json`, `pairs.json`, `spec.lock.json", "randomisation and spec hashes")):
        A("- `runs/%s/%s` - %s" % (doc["run_id"], f, d))
    A("")
    return "\n".join(L) + "\n"


def run(cfg) -> str:
    doc = util.read_json(cfg.p("analysis", "battery_summary.json"))
    text = render(cfg, doc)
    util.write_text(cfg.p("analysis", "analysis.md"), text)
    runner.record_stage(cfg, "battery-report",
                        {"stage": "battery-report", "finished_at": runner.now_iso()})
    return text
