"""Behavioural indicators computed mechanically from response text.

These are HEURISTIC PROXIES, not validated instruments. A response can check its work
without using any of the phrases below, and can use them without checking anything. They
are reported as observable surface behaviour and are never presented as evidence about
what a model is "doing" internally. Every report generated by this workflow repeats that
caveat; see METHODOLOGY.md, "Interpretation rule".
"""
from __future__ import annotations

import re
from typing import Any, Dict, List

FLAGS = re.IGNORECASE

MARKERS: Dict[str, List[str]] = {
    "verification": [
        r"\blet me (?:check|verify|confirm|re.?check)", r"\bdouble.?check", r"\bsanity check",
        r"\bverif(?:y|ying|ication)\b", r"\bcheck(?:ing)? (?:that|whether|the (?:answer|result|work))",
        r"\bto confirm\b", r"\bre.?read", r"\bcross.?check", r"\bvalidate (?:this|that|the)",
        r"\bsubstitut\w+ back", r"\bplugging (?:it|this) back", r"\bconsistent with the",
    ],
    "alternatives": [
        r"\balternative(?:ly)?\b", r"\banother (?:option|approach|way|possibility)",
        r"\bcould also\b", r"\binstead(?:,| we| you| one)", r"\boption [AB2]\b",
        r"\bon the other hand\b", r"\ba second (?:option|approach)", r"\btrade.?off",
    ],
    "caveats": [
        r"\bassum(?:e|ing|ption)", r"\bcaveat\b", r"\blimitation", r"\bnote that\b",
        r"\bhowever\b", r"\bif .{0,40}(?:differs|changes|is not)", r"\bdepends on\b",
        r"\bedge case", r"\bcorner case", r"\brisk(?:s)? (?:is|are|include)",
        r"\bnot (?:accounted|covered|handled)",
    ],
    "self_correction": [
        r"\bactually,", r"\bwait\b", r"\bon (?:second thought|reflection)", r"\bcorrection\b",
        r"\bi (?:was|had) (?:wrong|mistaken|too)", r"\bthat(?:'s| is) (?:wrong|incorrect|not right)",
        r"\brevis(?:e|ing|ed)\b", r"\blet me redo", r"\bscratch that", r"\bearlier i (?:said|wrote)",
        r"\bre.?examining", r"\bcorrecting (?:this|that|myself)",
    ],
}


def _distinct_markers(text: str, patterns: List[str]) -> int:
    return sum(1 for p in patterns if re.search(p, text, FLAGS))


def _total_markers(text: str, patterns: List[str]) -> int:
    return sum(len(re.findall(p, text, FLAGS)) for p in patterns)


def compute(task: Dict[str, Any], response: str,
            objective_result: Dict[str, Any] = None) -> Dict[str, Any]:
    text = response or ""
    words = re.findall(r"\b[\w'-]+\b", text)

    coverage_terms = task.get("coverage_terms", [])
    covered = [p for p in coverage_terms if re.search(p, text, FLAGS)]
    coverage = round(len(covered) / len(coverage_terms), 6) if coverage_terms else None

    out: Dict[str, Any] = {
        "response_chars": len(text),
        "response_words": len(words),
        "coverage": coverage,
        "coverage_hits": len(covered),
        "coverage_possible": len(coverage_terms),
    }
    for name, patterns in MARKERS.items():
        out["%s_markers" % name] = _distinct_markers(text, patterns)
        out["%s_marker_total" % name] = _total_markers(text, patterns)

    out["constraint_completion"] = (objective_result or {}).get("constraint_completion")
    out["planted_issue_recall"] = (objective_result or {}).get("planted_issue_recall")
    out["distractor_avoidance"] = (objective_result or {}).get("distractor_avoidance")
    return out


# Names used by the analysis stage, in report order.
INDICATOR_FIELDS = [
    "response_words",
    "coverage",
    "verification_markers",
    "alternatives_markers",
    "caveats_markers",
    "self_correction_markers",
    "constraint_completion",
]

INDICATOR_LABELS = {
    "response_words": "Response length (words)",
    "coverage": "Coverage of relevant considerations",
    "verification_markers": "Verification behaviour (distinct markers)",
    "alternatives_markers": "Alternatives considered (distinct markers)",
    "caveats_markers": "Important caveats identified (distinct markers)",
    "self_correction_markers": "Self correction (distinct markers)",
    "constraint_completion": "Constraint completion (objective)",
}
