"""Stage: report. Renders analysis.md from summary.json.

The report is generated, not written by hand, so the prose cannot drift from the numbers.
It is required to keep four things apart that are easy to blur:

  observed behavioural change   what the output looked like
  measured performance change   whether the task was actually done better
  statistical uncertainty       how much of this could be noise
  confounds                     what else could explain it

and to answer the three pre-registered questions separately: does the phrase beat control,
beat generic encouragement, and beat an explicit effort instruction.

No sentence generated here asserts that a model is motivated, wants anything, or tries
harder. See METHODOLOGY.md, "Interpretation rule".
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from . import indicators, judge, runner, util

PRIMARY_METRIC = "judge_task_success"

# A contrast counts as a demonstrated win only if the point estimate favours the treatment
# AND the interval excludes zero AND the Holm-adjusted permutation p is below 0.05. The
# rule is fixed in PREREGISTRATION.md before any data exists.
ALPHA = 0.05


def _f(x: Optional[float], nd: int = 3) -> str:
    return "n/a" if x is None else ("%.*f" % (nd, x))


def _ci(ci, nd: int = 3) -> str:
    if not ci:
        return "n/a"
    return "[%.*f, %.*f]" % (nd, ci[0], nd, ci[1])


def _verdict(contrast: Dict[str, Any], holm_p: Optional[float]) -> str:
    if not contrast.get("n_pairs"):
        return "no data"
    diff = contrast.get("task_level_mean_difference")
    ci = contrast.get("ci95_task_level")
    if diff is None:
        return "no data"
    excludes_zero = bool(ci) and (ci[0] > 0 or ci[1] < 0)
    significant = holm_p is not None and holm_p < ALPHA
    if diff > 0 and excludes_zero and significant:
        return "**Yes** - treatment higher, interval excludes zero, Holm adjusted p < %.2f" % ALPHA
    if diff < 0 and excludes_zero and significant:
        return "**No - worse.** Reference higher, interval excludes zero"
    direction = "higher" if diff > 0 else "lower" if diff < 0 else "level"
    reasons = []
    if not ci:
        reasons.append("no interval could be computed")
    elif not excludes_zero:
        reasons.append("the 95%% CI %s includes zero" % _ci(ci))
    if holm_p is None:
        reasons.append("no p value could be computed")
    elif not significant:
        reasons.append("the Holm adjusted p of %s is not below %.2f" % (_f(holm_p, 4), ALPHA))
    if diff < 0 and not reasons:
        reasons.append("the difference favours the reference condition")
    return "**Not demonstrated.** Treatment %s by %s, but %s." % (
        direction, _f(abs(diff)), " and ".join(reasons) or "the decision rule is not met")


def _condition_table(summary, metric, cfg) -> List[str]:
    rows = ["| Condition | n | Mean | 95% CI (cluster bootstrap over tasks) |",
            "|---|---:|---:|---|"]
    for cond in cfg.conditions:
        s = summary["conditions"][metric][cond["id"]]
        rows.append("| %s. %s | %d | %s | %s |" % (
            cond["id"], cond["name"].replace("_", " "), s["n"], _f(s["mean"]), _ci(s["ci95"])))
    return rows


def render(cfg, summary: Dict[str, Any]) -> str:
    counts = summary["counts"]
    meta = summary["run_meta"]
    mode = summary["mode"]
    is_pilot = mode == "pilot"
    L: List[str] = []
    A = L.append

    A("# Analysis: Experiment 001 - May the Force be with you")
    A("")
    A("*Generated by `scripts/experiment.py report` from `analysis/summary.json`. "
      "Do not edit by hand: re-run the stage instead.*")
    A("")
    if is_pilot:
        A("> **This is a PILOT run.** Its purpose is to prove the workflow end to end, not "
          "to answer the research question. With %d tasks it is not powered for inference, "
          "and no conclusion below should be read as evidence about the phrase. The "
          "confidence stage stays at **Observed**."
          % counts["tasks"])
        A("")

    # ---------------------------------------------------------------- 1
    A("## 1. What was run")
    A("")
    A("| Field | Value |")
    A("|---|---|")
    A("| Run ID | `%s` |" % summary["run_id"])
    A("| Mode | %s |" % mode)
    A("| Date | %s |" % meta.get("prepared_at"))
    A("| Generation model | `%s` |" % (meta.get("generation", {}).get("model")))
    A("| Generation backend | `%s` |" % (meta.get("generation", {}).get("backend")))
    A("| Judge model | `%s` |" % (meta.get("judging", {}).get("model")))
    A("| Sampling settings | %s |" % (meta.get("generation", {}).get("temperature", "not recorded")))
    A("| Master seed | `%s` |" % summary["seed"])
    A("| Tasks x conditions x repetitions | %d x %d x %d = %d |" % (
        counts["tasks"], counts["conditions"], counts["repetitions"],
        counts["expected_generations"]))
    A("| Generations present | %d |" % counts["generations_present"])
    A("| Blind judgments | %d |" % counts["blind_judged"])
    A("| Pairwise comparisons | %d |" % counts["pairwise_judged"])
    A("| Task set version | `%s` |" % summary["spec_lock"]["versions"].get("tasks"))
    A("| Rubric version | `%s` |" % summary["spec_lock"]["versions"].get("rubric"))
    A("| Prompt version | `%s` |" % summary["spec_lock"]["versions"].get("prompt_version"))
    A("| Evaluation version | `%s` |" % summary["spec_lock"]["versions"].get("evaluation_version"))
    A("")
    A("Conditions, differing only in text appended to an otherwise identical base prompt:")
    A("")
    A("| ID | Name | Appended text |")
    A("|---|---|---|")
    for cond in cfg.conditions:
        A("| %s | %s | %s |" % (cond["id"], cond["name"].replace("_", " "),
                                ("*(nothing)*" if not cond["suffix"] else "`%s`" % cond["suffix"])))
    A("")

    # ---------------------------------------------------------------- 2
    A("## 2. Observed behavioural change")
    A("")
    A("What the responses looked like. These are **surface measurements of text**, computed "
      "by regular expressions over the output. They are heuristic proxies: a response can "
      "check its work without using any of the marker phrases, and can use the phrases "
      "without checking anything. Read them as description, not as measurement of effort.")
    A("")
    header = "| Indicator | " + " | ".join(
        "%s. %s" % (c["id"], c["name"].replace("_", " ")) for c in cfg.conditions) + " |"
    A(header)
    A("|---" * (len(cfg.conditions) + 1) + "|")
    for field in indicators.INDICATOR_FIELDS:
        cells = []
        for cond in cfg.conditions:
            s = summary["conditions"].get(field, {}).get(cond["id"], {})
            cells.append(_f(s.get("mean"), 2 if field == "response_words" else 3))
        A("| %s | %s |" % (indicators.INDICATOR_LABELS[field], " | ".join(cells)))
    A("")

    # ---------------------------------------------------------------- 3
    A("## 3. Measured task performance change")
    A("")
    A("Whether the task was actually done better. Two independent measurements: a "
      "deterministic objective score from planted issues and machine-checkable "
      "constraints, and a blind judge's **task success** rating, which is the "
      "pre-registered primary outcome.")
    A("")
    A("### 3.1 Objective score (deterministic, no judge involved)")
    A("")
    L.extend(_condition_table(summary, "objective_score", cfg))
    A("")
    A("### 3.2 Blind judge, task success (primary outcome, 1-5)")
    A("")
    L.extend(_condition_table(summary, PRIMARY_METRIC, cfg))
    A("")
    A("### 3.3 Blind judge, secondary dimensions (1-5)")
    A("")
    dims = [d for d in judge.DIMENSIONS if d != "task_success"]
    A("| Dimension | " + " | ".join("%s" % c["id"] for c in cfg.conditions) + " |")
    A("|---" * (len(cfg.conditions) + 1) + "|")
    for d in dims:
        cells = [_f(summary["conditions"]["judge_%s" % d][c["id"]]["mean"], 2)
                 for c in cfg.conditions]
        A("| %s | %s |" % (d.replace("_", " "), " | ".join(cells)))
    A("")
    A("### 3.4 Pairwise preference (secondary)")
    A("")
    A("Blind head to head comparisons within the same task and repetition, with A/B "
      "presentation order randomised from the master seed before judging began.")
    A("")
    A("| Contrast | Treatment wins | Reference wins | Ties | Win rate excl. ties | 95% CI | p (exact binomial) |")
    A("|---|---:|---:|---:|---:|---|---:|")
    for cid, p in summary["pairwise"].items():
        A("| %s | %d | %d | %d | %s | %s | %s |" % (
            cid, p["treatment_wins"], p["reference_wins"], p["ties"],
            _f(p["treatment_win_rate_excluding_ties"]), _ci(p["ci95_win_rate"]),
            _f(p["p_binomial_excluding_ties"], 4)))
    A("")
    slot_rates = [p.get("slot_a_preference_rate") for p in summary["pairwise"].values()
                  if p.get("slot_a_preference_rate") is not None]
    if slot_rates:
        A("Slot A was preferred %s of the time across all comparisons. A value far from "
          "0.5 indicates position bias in the judge rather than a difference between "
          "conditions; the randomised slot assignment is what keeps that bias from "
          "loading onto one condition." % _f(sum(slot_rates) / len(slot_rates)))
        A("")

    # ---------------------------------------------------------------- 4
    A("## 4. Statistical uncertainty")
    A("")
    A("Pairing is within (task, repetition). Paired differences are averaged to the task "
      "level, and the **task** is the unit for both the permutation test and the bootstrap, "
      "because responses to the same task are not independent. The permutation test flips "
      "the sign of each task level difference, which is the exchangeability assumption "
      "implied by the null hypothesis that the appended text does nothing. p values are "
      "Holm adjusted across the three pre-registered contrasts.")
    A("")
    for metric, label in ((PRIMARY_METRIC, "Primary outcome: blind judge task success"),
                          ("objective_score", "Objective score")):
        A("**%s**" % label)
        A("")
        A("| Contrast | Tasks | Mean difference | 95% CI | Cohen's dz | p (unadj.) | p (Holm) |")
        A("|---|---:|---:|---|---:|---:|---:|")
        for c in cfg.primary_contrasts:
            k = summary["contrasts"][metric][c["id"]]
            holm_p = summary["holm_adjusted_primary_contrasts"][metric].get(c["id"])
            A("| %s | %s | %s | %s | %s | %s | %s |" % (
                c["id"], k.get("n_tasks", 0), _f(k.get("task_level_mean_difference")),
                _ci(k.get("ci95_task_level")), _f(k.get("cohens_dz_task_level"), 2),
                _f(k.get("p_permutation_task_level"), 4), _f(holm_p, 4)))
        A("")
    if counts["tasks"] < 20:
        A("With %d tasks the permutation test cannot produce a p value below %.4f no matter "
          "how consistent the direction is. Absence of a significant result here is "
          "uninformative." % (counts["tasks"], 2.0 / (2 ** counts["tasks"])))
        A("")

    # ---------------------------------------------------------------- 5
    A("## 5. Possible confounds")
    A("")
    echo = summary["blinding"]
    A("- **Blinding leakage.** %d of %d responses (%s) repeated their condition's text "
      "back in the output, which a judge could in principle recognise. Outputs were never "
      "edited. %s" % (echo["condition_echo_count"], counts["generations_present"],
                      _f(echo["condition_echo_rate"]),
                      "This is currently the largest threat to the blind."
                      if (echo["condition_echo_rate"] or 0) > 0.05 else
                      "At this rate the effect on the blind is small."))
    A("- **Prompt length.** Condition A is shorter than B, C and D by construction, because "
      "it has nothing appended. Any difference between A and the others could be a response "
      "to a longer prompt rather than to the meaning of the added text. The B and D "
      "conditions exist precisely so that C can be compared against added text of similar "
      "length, which is the comparison that isolates the phrase.")
    A("- **Judge model.** The judge is `%s` and the generator is `%s`.%s" % (
        meta.get("judging", {}).get("model"), meta.get("generation", {}).get("model"),
        " These are the same model, so a preference for its own output style cannot be "
        "ruled out." if meta.get("judging", {}).get("model") ==
        meta.get("generation", {}).get("model") else ""))
    A("- **Length bias in judging.** Judges commonly prefer longer answers. Section 2 "
      "reports mean response length per condition; if one condition is systematically "
      "longer, part of any judge based difference may be length rather than quality. The "
      "objective score in 3.1 is immune to this and is the better check.")
    A("- **Harness context.** Generations ran through the `claude` CLI, which supplies its "
      "own system preamble and tool descriptions. That preamble is identical across "
      "conditions, so internal validity holds, but these results describe behaviour in "
      "that harness rather than of a bare model API call.")
    A("- **Sampling settings.** %s" % (meta.get("generation", {}).get("temperature",
      "Not exposed by this backend, so run to run variation cannot be attributed to a "
      "known temperature.")))
    A("- **Heuristic indicators.** Everything in section 2 is regular expression counting "
      "over text. It measures phrasing, not cognition.")
    A("- **Single model, single phrase position.** The phrase was appended at the end of "
      "the prompt, to one model. Nothing here generalises to other positions or models "
      "without a replication.")
    A("- **Multiplicity.** Six judge dimensions, seven indicators and several metrics are "
      "reported. Only the primary outcome with its Holm adjusted contrasts should be read "
      "as a test; the rest are descriptive.")
    A("")

    # ---------------------------------------------------------------- 6
    A("## 6. The three questions")
    A("")
    A("Decision rule, fixed in `PREREGISTRATION.md` before any data existed: a contrast "
      "counts as demonstrated only if the treatment's point estimate is higher, the 95%% "
      "interval excludes zero, and the Holm adjusted permutation p is below %.2f, on the "
      "primary outcome." % ALPHA)
    A("")
    labels = {
        "C_vs_A": "Does \"May the Force be with you.\" beat **Control** (no added text)?",
        "C_vs_B": "Does it beat **generic encouragement** (\"Good luck. Do your best.\")?",
        "C_vs_D": "Does it beat an **explicit effort instruction**?",
    }
    for c in cfg.primary_contrasts:
        k = summary["contrasts"][PRIMARY_METRIC][c["id"]]
        holm_p = summary["holm_adjusted_primary_contrasts"][PRIMARY_METRIC].get(c["id"])
        A("### %s" % labels.get(c["id"], c["id"]))
        A("")
        A("%s" % _verdict(k, holm_p))
        A("")
        A("- Primary outcome difference: %s (95%% CI %s), Holm adjusted p = %s"
          % (_f(k.get("task_level_mean_difference")), _ci(k.get("ci95_task_level")),
             _f(holm_p, 4)))
        ok = summary["contrasts"]["objective_score"][c["id"]]
        A("- Objective score difference: %s (95%% CI %s)"
          % (_f(ok.get("task_level_mean_difference")), _ci(ok.get("ci95_task_level"))))
        pw = summary["pairwise"].get(c["id"], {})
        A("- Pairwise win rate excluding ties: %s (95%% CI %s)"
          % (_f(pw.get("treatment_win_rate_excluding_ties")), _ci(pw.get("ci95_win_rate"))))
        A("")

    # ---------------------------------------------------------------- 7
    A("## 7. Interpretation rule")
    A("")
    A("This experiment measures text. It does not measure motivation.")
    A("")
    A("Where this repository uses the words *motivation*, *effort* or *seriousness*, they "
      "name hypotheses about observable output behaviour: more complete reasoning, more "
      "checking, better constraint following, fewer errors, higher task success. They are "
      "not claims that a model wants anything, tries harder, or experiences encouragement. "
      "A difference between conditions here would show that a string of text changed a "
      "distribution over outputs. That is a fact about prompting, not about inner life.")
    A("")
    A("## 8. Confidence stage")
    A("")
    if is_pilot:
        A("Current stage: **Observed**. A pilot validates the workflow and cannot move the "
          "stage. Moving to **Tested** requires the full run: %d tasks, 4 conditions, 3 "
          "repetitions, 240 generations." % 20)
    else:
        A("Current stage: **Observed**. Promotion to **Tested** is a judgement to record by "
          "hand in the experiment README after reading the results above, not something "
          "this script asserts.")
    A("")
    A("## Raw data")
    A("")
    A("- `runs/%s/raw/` - every generation, write once, with `INDEX.jsonl` as a sha256 ledger" % summary["run_id"])
    A("- `runs/%s/analysis/samples.csv` - one row per generation" % summary["run_id"])
    A("- `runs/%s/analysis/results.csv` - aggregate metrics and contrasts" % summary["run_id"])
    A("- `runs/%s/analysis/summary.json` - the machine readable result this report renders" % summary["run_id"])
    A("- `runs/%s/manifest.json`, `pairs.json`, `spec.lock.json` - randomisation and spec hashes" % summary["run_id"])
    A("")
    return "\n".join(L) + "\n"


def run(cfg) -> str:
    summary = util.read_json(cfg.p("analysis", "summary.json"))
    text = render(cfg, summary)
    util.write_text(cfg.p("analysis", "analysis.md"), text)
    runner.record_stage(cfg, "report", {"stage": "report", "finished_at": runner.now_iso()})
    return text
